import './globals.css'
import MainToolbar from './components/common/MainToolBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <MainToolbar></MainToolbar>
      <body>{children}</body>
    </div>
  )
}
